config/routes.rb
Singlemessaging::Application.routes.draw do
  scope "(:locale)", :locale => /en|hi/ do
    resources :oauths, :only => [:destroy, :index] do
       get :generate, :on => :collection
    end

    match '/auth/:provider/callback' => 'authentication#create'
    get "authentication/index"
    get "authentication/fill_email"
    post "authentication/change_email"
    get "authentication/create"

    get "authentication/destroy"
   # get "sessions/new"
    get "sessions/create"
    #get "sessions/destroy"
    #get "sessions/set_locale"
    get "sessions/faq"


    match "/inbox" => "messages#inbox", :as =>"inbox", :via =>"get"
    match "/reply" => "messages#reply", :as =>"reply", :via =>"post"
    resources :messages, :except => [ :update,:index] do
      member do
        get :downloads
      end
      collection do
        get 'destroy' => :destroy
        put :index_delete
        put :show_delete
        get :drafts
        get :outbox
        put :flag
        put :send_draft  
      end 
    end 


    resources :users, :except => [:destroy, :show, :index] do
       get :autocomplete_user_name, :on => :collection
      collection do   
        get :change_time_zone 
        put :update_time_zone 
        get :change_avatar 
        put :update_picture
        get :change_notification 
        put :update_notification
        get :user_verify 
        get :send_password
      end 
    end

    controller :sessions do
    	get 'login' => :new
    	post 'login' => :create
    	get 'logout' => :destroy
    end

    root :to => 'sessions#new' 
  end
  match '/:locale' => 'sessions#new' , :as => "/login"

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content , :sender_id, :subject, :assets_attributes, :flagged
  
  
  has_many :assets, :dependent => :destroy, :autosave => true
  belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
  has_many :receivers, :dependent => :destroy
  belongs_to :parent, :class_name => "Message", :foreign_key => "parent_id"
  has_many :flag_messages, :dependent => :destroy
  

  define_index do
    indexes subject, :sortable => true
    indexes content
    indexes sender(:name), :as => :sender
    #indexes author(:name), :as => :author, :sortable => true

    has  created_at, updated_at
  end

  validates :sender_id, :presence=> true

  MESSAGE_STATUS = { "Draft" => 0,"BothDelete" => 4, "AvailableBoth"=>1,"SenderDelete" => 2,
           "ReceiverDelete" => 3          
         }
  
  
  accepts_nested_attributes_for :assets , :reject_if => lambda {|a| a[:document].blank? }
  
  #   sphinx_scope(:inbox) { |user|
  #    includes(:sender, :receivers).listing.sent.where("r.user_id =? and r.status in (1,2)",user.id).join_with_receiver.group("parent_id") 
  # }

  
  scope :inbox, lambda{ |user| includes(:sender, :receivers).listing.sent.where("r.user_id =? and r.status in (1,2)",user.id).join_with_receiver.group("parent_id") }
   
  scope :outbox, lambda{ |user| includes(:sender, :receivers => :user).listing.sent.where("sender_id =? and r.status in (1,3)",user.id).join_with_receiver.group("parent_id") }
  
  scope :drafts, lambda{ |user| listing.where("sender_id = ? and r.status = ?", user.id, MESSAGE_STATUS["Draft"]).join_with_receiver.group("parent_id") }
  
  scope :showing_to_sender, lambda { |parentmessage, owner| includes(:sender, :assets).showing.where("(parent_id =?) and (( sender_id = ? and status in (1, 3)) or (sender_id != ? and status in (1, 2)))",parentmessage.id, owner.id, owner.id ).join_with_receiver.group("messages.id")
 }
   scope :showing_to_receiver, lambda { |parentmessage, owner, receiver| includes(:sender,:assets).showing.where("(parent_id = ?) and (( sender_id = ? and status in (1, 2)) or (sender_id =? and status in (1, 3)))",parentmessage.id,owner.id,receiver.id ).join_with_receiver.group("messages.id")
 }

  scope :listing, order('messages.updated_at DESC').select("messages.id , sender_id , messages.updated_at , subject")
  
  scope :showing, order('messages.created_at DESC').select(" messages.id , sender_id , messages.created_at , content , subject ")

  scope :sent, where('r.status !=?',MESSAGE_STATUS["Draft"])

  scope :join_with_receiver, joins("inner join receivers as r on r.message_id = messages.id")
  
  
  default_scope where( :flagged => false) 
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :email, :name, :password_digest, :time_zone
  attr_accessible :password, :password_confirmation, :avatar, :notification
  attr_accessible :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at
  
 
  has_many :messages#, :dependent => :destroy
  has_many :flag_messages, :dependent => :destroy
  has_many :receivers, :dependent => :destroy
  has_many :authentications
  has_many :oauths
  
  
  validates_attachment_size :avatar, :less_than=>1.megabyte, :message => "Image size too large"
  validates_attachment_content_type :avatar, :content_type=>['image/jpeg', 'image/png', 'image/gif', 'image/jpg'], :message => "Please upload a image of jpg/png format"
  validates :name, :presence => true,:length => { :minimum => 3,:tokenizer => lambda {|str| str.scan(/[a-z]/i)}}
  validates :email, :uniqueness => {:case_sensitive => false}, :presence => true 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :age, :numericality => {:only_integer => true ,:greater_than => 0 , :less_than => 100 },:allow_nil => true
  validates :password, :presence => true,:length => { :minimum => 6 }, :if => :password
  
  has_attached_file :avatar ,:styles => {:small => "120x120>",:thumb => "50x50>"}
  
  has_secure_password 
  

  after_create :welcome
 
  scope :join_with_receiver, joins("as u inner join receivers as r on r.user_id = u.id")
  
  def name_with_email
     user = User.find self.id
    "#{self.name}<#{user.email}>"
  end


  def apply_omniauth(omniauth)
    if omniauth['provider'] != 'twitter'
      self.email = omniauth['info']['email'] if email.blank?
    end  
    self.name  = omniauth['info']['name'] if name.blank?
    self.notification = "1"
    self.time_zone = "New Delhi"
    self.password = self.password_confirmation = self.name
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid']) 
  end

  def welcome
    Notifier.delay.welcome_message(self)
  end  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 
  skip_before_filter :authorize_through_json, :except => [:inbox, :destroy, :create]
  autocomplete :user, :name, :display_value => :name_with_email
  protect_from_forgery :except => :destroy
  def outbox
    @messages = Message.outbox(current_user).page(params[:page]).per(10)
    
  end
  
  def edit
    @message = Message.includes(:receivers).find(params[:id])
    if @message.sender != current_user
       flash[:notice]= 'You are not authorized for this' 
       redirect_to inbox_path
    end
    session[:edit_message] = params[:id]
    @receivers = []
    @message.receivers.each do |receiver|
      @receivers << receiver.user.name
    end
    @receivers = @receivers.join(', ') 
  end
  
  def send_draft
    @message = Message.find(session[:edit_message])
    if @message.sender != current_user
       flash[:notice]= 'You are not authorized for this' 
       redirect_to inbox_path 
    end
    @message.content = params[:message][:content]
    @message.created_at=Time.now
    @message.save
    @message.receivers.each do |receiver|
      if params[:commit] == "send"
        receiver.status = Message::MESSAGE_STATUS["AvailableBoth"]
      else
        receiver.status = Message::MESSAGE_STATUS["Draft"]
      end 
      receiver.save
    end

    respond_to do |format| 
      if params[:commit] != "send"
        format.html { redirect_to inbox_path, notice: 'Message was Saved in drafts' }
      else
        format.html { redirect_to inbox_path, notice: 'Message was Sent' }
      end
      format.json { render json: @message, status: :created, location: @message }
    end

  end
  
  def inbox
    #@messages = Message.inbox(current_user).search params[:search] 
    @messages = Message.inbox(current_user).page(params[:page]).per(10)
    respond_to do |format|
      format.html 
      format.json { render json: @messages }
    end
  end
 
  def drafts
    @messages = Message.drafts(current_user).page(params[:page]).per(10)
  end
  
  def downloads
    @asset = Asset.find(params[:id])
    send_file @asset.document.path, :type => @asset.document_content_type
  end

  def flag
    @message = Message.find session[:message_id]
    count = 0 
    if ! FlagMessage.find_by_user_id_and_message_id(current_user.id, @message.id)
      count = 1
      FlagMessage.create(:user_id => current_user.id, :message_id => @message.id)
    end
    respond_to do |format|
     if  count == 1
        format.html { redirect_to inbox_path, notice: 'You flagged it' }
        format.json { render json: @message, status: :created, location: @message }
     else
        flash[:error] = 'You have already flagged it '
        format.html { redirect_to request.referrer }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end 
  end
  
  
  def reply
    @message = Message.new(params[:message])
    @message.sender = current_user
    @message.parent_id = session[:message_id]
    parentmessage = Message.find @message.parent_id
    parentmessage.touch
    @message.subject=parentmessage.subject
    @message.save
    array_of_user = []
    if parentmessage.sender != current_user
       array_of_user = [parentmessage.sender_id]
    else
       array_of_user = Receiver.find_all_by_message_id(session[:message_id]).collect(&:user_id)
    end
    create_receivers(array_of_user,@message,"reply")
    respond_to do |format|
       if @message.save
         flash[:notice] = params[:commit] != "send" ? 'Message was Saved in drafts' : "Message was Sent " 
         format.html { redirect_to inbox_path }
         format.json { render json: @message, status: :created, location: @message }
       else
         flash[:error] = 'Something went wrong '
         format.html { redirect_to message_path }
         format.json { render json: @message.errors, status: :unprocessable_entity }
       end
    end
  end
  

  def show
    message = Message.find (params[:id])  
    if !(message.sender_id == current_user.id) && !(message.receivers.exists?( :user_id => current_user.id)) 
       flash[:error] = "you are not authorized to view this "
       redirect_to inbox_url 
       return
    end  
    parentmessage = Message.find message.parent_id
    session[:message_id] = parentmessage.id
    @sender = parentmessage.sender.name
    @subject = parentmessage.subject
    # changing the read 

    if message.receivers.where("user_id = ?",current_user.id).where(:read => false).update_all(:read => true ) > 0 
      flash.notice = "expired"
      expire_fragment("inbox_#{current_user.id}_#{Message.inbox(current_user).first.updated_at}")
    end
    if parentmessage.sender == current_user
       @receiver = User.select("u.name").where("r.message_id= ?",parentmessage.id).join_with_receiver.collect(&:name).join(', ')
       @messages = Message.showing_to_sender(parentmessage,parentmessage.sender)
    
    else

       @receiver = current_user.name
       @messages = Message.showing_to_receiver(parentmessage,parentmessage.sender,current_user)
    end  
    @message = Message.new
    @message.assets.build
  end

  def new
    @message = Message.new
    @message.assets.build
  end

  def create_receivers(array_of_users,message,received)
    count =0
    array_of_users.each do |num|
      @receiver = Receiver.new
      if params[:commit] == "send"
        @receiver.status = Message::MESSAGE_STATUS["AvailableBoth"]
        @receiver.read = 'false'
      else
        @receiver.status = Message::MESSAGE_STATUS["Draft"]
      end   
      if received != "reply"
        @receiver.user = User.find_by_email(num)
        
      else
        @receiver.user = User.find(num) 
      end  
        @receiver.message = message
        
      if @receiver.user == nil
         count+=1
      else
         @receiver.save
      end  
    end
    count    
  end

  def create

    array_of_user = [] 
    count = 0
    wrong_users = 0
    @message = Message.new(params[:message])
    if params[:message][:sender_id].length > 1 && params[:message][:subject].length > 1
      count = 1
      temporary = params[:message][:sender_id].split(">;")
      temporary.each do |val|
        array_of_user << val.split('<')[1]
      end
      array_of_user.uniq!
      
      @message.sender = current_user
      @message.save
      @message.update_attribute(:parent_id , @message.id)
      wrong_users = create_receivers(array_of_user, @message, "create")
    end  
    
    respond_to do |format|
      if  count == 1 && @message.save && @message.receivers.count != 0
        if wrong_users > 0
          flash[:alert]= "#{wrong_users} of the recipeients doesn't exists"
        end
        flash[:notice] = params[:commit] != "send" ? 'Message was Saved in drafts' : "Message was Sent "
        format.html { redirect_to inbox_path }
        format.json { render :text => flash[:notice] }
      elsif count == 0
         flash.now[:error] = params[:message][:subject].length < 1 ? 'Subject is empty' : 'Mention atleast one recepent'
         format.html { render action: "new" }
         format.json { render :json => flash.now[:error], :status => 406 }
      elsif @message.receivers.count == 0
         @message.destroy
         @message = Message.new(params[:message])
         flash.now[:error] = 'Invalid receiver'
         format.html { render action: "new" }
         format.json { render :json => flash.now[:error], :status => 406 }
      else
         format.html { render :text => "something went wrong"  }
         format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
  

  def index_delete
     @messages = Message.find(params[:message_ids])
     expire_fragment("inbox_#{current_user.id}_#{Message.inbox(current_user).first.updated_at}")
     @messages.each do |message|

        childmessages = Message.find_all_by_parent_id(message.parent_id)   
        childmessages.each do |childmessage|
         update_receivers(childmessage)
        end
     end  
     respond_to do |format|
       format.html { redirect_to request.referrer,:notice => "Selected Messages Deleted"}
     end
  end 
  

  def show_delete
     @messages = Message.find(params[:message_ids])
     @messages.each do |message|
        update_receivers(message)
     end  
     respond_to do |format|
       format.html { redirect_to request.referrer,:notice => "Selected Messages Deleted"}
     end
  end

  def update_receivers(message)
    if message.sender == current_user
       receivers=Receiver.find_all_by_message_id(message.id)
         receivers.each do |receiver|
         if receiver.status == Message::MESSAGE_STATUS["Draft"]
            message.destroy
            break;        
         elsif receiver.user_id == message.sender_id || receiver.status == Message::MESSAGE_STATUS["ReceiverDelete"]
             receiver.status = Message::MESSAGE_STATUS["BothDelete"]
             receiver.save   
         elsif receiver.status == Message::MESSAGE_STATUS["AvailableBoth"]
             receiver.status = Message::MESSAGE_STATUS["SenderDelete"]
             receiver.save
      
         end
       end          
    else
      receiver=Receiver.find_by_message_id_and_user_id(message.id,current_user.id)
      if receiver.status == Message::MESSAGE_STATUS["AvailableBoth"]
          receiver.status = Message::MESSAGE_STATUS["ReceiverDelete"]
      elsif receiver.status == Message::MESSAGE_STATUS["SenderDelete"]
          receiver.status = Message::MESSAGE_STATUS["BothDelete"]
      end
      receiver.save          
    end
  end  
  
  def destroy
    @message = Message.find(params[:id])
    update_receivers(@message)
    respond_to do |format|
      expire_fragment("inbox_#{current_user.id}_#{Message.inbox(current_user).first.updated_at}")
      format.html { redirect_to request.referrer }
      format.json { head :no_content }
    end
  end
end

app/views/messages/_asset_fields.html.erb
 <div class="fields">
 <%= f.label :document,"Attach a file" %> 
 <%= f.file_field :document %><br />
 </div>

app/views/messages/_form.html.erb
   <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content,:cols=>116,:rows=>6 %>
  </div>
  <%= f.fields_for :assets do |builder| %>
         <%= render "asset_fields",:f => builder %>
        
   <% end %>
  <p><%= f.link_to_add "Add a Attachment", :assets %></p>

  <%= f.submit 'send', :class => "create" %>
  <%= f.submit 'save to drafts', :class => "create" %> 

  

app/views/messages/_main.html.erb
<%= form_tag index_delete_messages_path,:method => :put do %>
<%#= paginate @messages %>
<% if @messages.length > 0  %>
  <table WIDTH="90%" id="center">
    <tr>
      <th><%= check_box_tag :checkall %></th>
      <th colspan >From</th>
      <th colspan > To</th>
      <th colspan > Subject</th>
      <th colspan >Date</th>
      <th colspan ></th>
    </tr>

   <% @messages.each do |message| %>
     <tr class="read">
     <% for receiver in message.receivers %>
          <% if receiver.user_id.to_s == session[:user_id].to_s && !receiver.read %>
               <tr class="unread">
          <%end%>
     <%end%>  
     <td><%= check_box_tag "message_ids[]", message.id %></td>
     <td colspan >  <%= message.sender.name %></td>
     <td colspan > 
        <% if message.sender_id.to_s == session[:user_id].to_s %>
          <% r=""%>
          <%for receiver in message.receivers %>
             <% r += receiver.user.name + ", "  %>
          <%end%>
          <%=r[0..-3]%>
        <% else %>
          <%= User.find(session[:user_id]).name %>  
        <%end%>   
     <td colspan ><%= link_to message.subject, message %></td>
     <td colspan ><%= message.updated_at.ctime %></td>
    </tr>
   <% end %>
  </table>
<br />
<% else %>
<h3> Nothing for you</h3>
<%end%>
<%= submit_tag "Delete Checked",:class => 'create' %>
<% end %>

<%= javascript_include_tag "jquery-1.8.0.min.js"  %>
<%= javascript_include_tag "checking.js" %>

app/views/messages/draft_index.html.erb
<% if notice !=nil %>
  <p id="notice"><%= notice %></p>
<%end%>
<h1>Listing Drafts</h1>
<%= paginate @messages %>
<table>
  <tr>
    <th>Content</th>
    <th> Date</th>
    <th></th>
    <th></th>
  </tr>
<% @messages.each do |message| %>
  <tr> 
    <td><%= message.subject %></td>
    <td><%= message.updated_at.ctime %></td>
    <td><%= link_to 'edit' ,edit_draft_message_url(message.id)%></td>
    <td><%= link_to 'Delete', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

app/views/messages/drafts.html.erb
<h1>Listing Drafts</h1>
<%= form_tag show_delete_messages_path,:method => :put do %>
<% if @messages.length > 0  %>
<%= paginate @messages %>
<table WIDTH="90%" id="center">
  <tr>
    <th><%= check_box_tag :checkall %></th>
    <th>Content</th>
    <th> Date</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
<% @messages.each do |message| %>
  <tr> 
    <td><%= check_box_tag "message_ids[]", message.id %></td>
    <td><%= message.subject %></td>
    <td><%= message.updated_at.ctime %></td>
    <td><%= link_to 'edit' ,edit_message_path(message.id)%></td>
    <td><%= link_to "Delete", messages_url({:id => message.id}) %></td>
  </tr>
<% end %>
</table>
<br />
<% else %>
<h3> Nothing for you</h3>
<%end%>
<%= submit_tag "Delete Checked",:class => 'create' %>
<%end %>
<%= javascript_include_tag "jquery-1.8.0.min.js"  %>
<%= javascript_include_tag "checking.js" %>

app/views/messages/edit.html.erb
<fieldset id="outer">
<legend>Draft</legend>
  <%= form_for @message, :html => {:multipart => true} ,:url => send_draft_messages_path, :method =>"put" do |f| %>

   To: <%=@receivers%>  <br><br>
   Subject: <%=@message.subject%><br><br>
   <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content,:cols=>116,:rows=>6 %>
    </div>
    <% for asset in @message.assets %>
       <%=link_to asset.document_file_name , downloads_message_path(asset.id) %> <br>
    <%end%>
    <%= f.submit 'send', :class => "create" %>
    <%= f.submit 'save to drafts', :class => "create" %>
  <% end %>
</fieldset>
<%= link_to 'Back', drafts_messages_path %>

app/views/messages/edit_draft.html.erb
<% if notice !=nil %>
 <p id="notice"><%= notice %></p>
<%end%>
<fieldset id="outer">
<legend>Draft</legend>
  <%= form_for @message, :html => {:multipart => true} ,:url => send_draft_messages_url, :method =>"put" do |f| %>

   To: <%=@receivers%>  
   <div class="field">
     <%= f.label :subject %>&nbsp;&nbsp;
     <%= f.text_field :subject,:size=> 70 %>
   </div>
   <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content,:cols=>116,:rows=>6 %>
    </div>
    <% for asset in @message.assets %>
       <%=link_to asset.document_file_name , downloads_message_url(asset.id) %> <br>
    <%end%>
    <%= f.submit 'send', :class => "create" %>
    <%= f.submit 'save to drafts', :class => "create" %>
  <% end %>
</fieldset>
<%= link_to 'Back', messages_path %>

app/views/messages/inbox.html.erb
<h1>INBOX</h1>
<% cache("inbox_#{current_user.id}_#{@messages.first.updated_at}") do %>
<%= render "main" %>
<% end %>

app/views/messages/new.html.erb
<%- content_for(:head) do -%>
<%= javascript_include_tag "jquery-1.8.0.min.js"  %>
<%= javascript_include_tag "jquery-ui-1.8.23.custom.min.js"  %>
<%= javascript_include_tag "autocomplete-rails.js" %>
<%= javascript_include_tag "nested_form.js" %>
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/ui-lightness/jquery-ui.css" %>
<%- end -%>

<fieldset id="outer">
  <legend>New message</legend>
  <%= nested_form_for @message  do |f| %>
    Send To <%= f.autocomplete_field :sender_id, autocomplete_user_name_users_path ,:"data-delimiter" => ';',:size=> 110%>
  <div class="field">
    <%= f.label :subject %>&nbsp;&nbsp;
    <%= f.text_field :subject,:size=> 110 %>
  </div>
    <%= render :partial => 'form',
           :locals => {:f => f}
%>
  <% end %>
</fieldset>
<%= link_to 'Back', inbox_url %>

app/views/messages/outbox.html.erb
<h1>OUTBOX</h1>

<%= render "main" %>

app/views/messages/show.html.erb
<%- content_for(:head) do -%>
<%= javascript_include_tag "jquery-1.8.0.min.js"  %>
<%= javascript_include_tag "messages.js.coffee" %>
<%= javascript_include_tag "nested_form.js" %>

<%- end -%>
<h4> From :&nbsp;&nbsp;&nbsp;<%=@sender%><br>
  To :&nbsp;&nbsp;&nbsp;<%=@receiver%><br>
</h4>
<h5>
Subject :&nbsp;<%=@subject%>
</h5>
<div id="right">
  <%= button_to 'Flag', flag_messages_path, method: "put", :class =>"create" %>
</div>


<%= form_tag show_delete_messages_path,:method => :put do %>
 <%= check_box_tag :checkall %>
 <table>
 <% @messages.each do |message| %>
   <tr>
   <td><%= check_box_tag "message_ids[]" , message.id %></td>
   <td colspan = "56">
   <fieldset id = "<%= cycle('odd', 'even') %>">
        
        <table>
        <tr><td><h4>From:&nbsp;&nbsp;&nbsp;<%= message.sender.name %></td></h4><td>
        <% if message.sender.avatar.exists? %>
          <%= image_tag message.sender.avatar.url(:thumb) %>
        <% else %>
          <%= image_tag("noimage.gif") %>
        <% end %>
          </td></tr></table>
    <div id="right">
      <%= message.created_at.ctime %>
    </div>
    Message
    <div id="content">
    <%= message.content.gsub(/\n/, '<br/>').html_safe %>
    </div>
    
    <br>
    <% for asset in message.assets %>
       <%=link_to asset.document_file_name , downloads_message_path(asset.id) %> <br>
    <%end%> 
    <%= link_to "Delete", messages_url({:id => message.id}) %>
   
   </fieldset> 
 </td>
</tr>
  <% end %>
</table>
<%= submit_tag "Delete Checked",:class => 'create' %>
<%end %>
<br />
<button id="buttonreply" class="create">Reply</button>
<div id="replying" >

  <fieldset id="outer">
   <%= nested_form_for @message,:url => reply_path ,:multipart => true, :method => "post"  do |f| %>
     <%= render :partial => 'form',
           :locals => {:f => f}%>
   <%end%>
  </fieldset>
</div>
<%= javascript_include_tag "checking.js" %>