config/routes.rb
Singlemessaging::Application.routes.draw do
  scope "(:locale)", :locale => /en|hi/ do
    resources :oauths, :only => [:destroy, :index] do
       get :generate, :on => :collection
    end

    match '/auth/:provider/callback' => 'authentication#create'
    get "authentication/index"
    get "authentication/fill_email"
    post "authentication/change_email"
    get "authentication/create"

    get "authentication/destroy"
   # get "sessions/new"
    get "sessions/create"
    #get "sessions/destroy"
    #get "sessions/set_locale"
    get "sessions/faq"


    match "/inbox" => "messages#inbox", :as =>"inbox", :via =>"get"
    match "/reply" => "messages#reply", :as =>"reply", :via =>"post"
    resources :messages, :except => [ :update,:index] do
      member do
        get :downloads
      end
      collection do
        get 'destroy' => :destroy
        put :index_delete
        put :show_delete
        get :drafts
        get :outbox
        put :flag
        put :send_draft  
      end 
    end 


    resources :users, :except => [:destroy, :show, :index] do
       get :autocomplete_user_name, :on => :collection
      collection do   
        get :change_time_zone 
        put :update_time_zone 
        get :change_avatar 
        put :update_picture
        get :change_notification 
        put :update_notification
        get :user_verify 
        get :send_password
      end 
    end

    controller :sessions do
    	get 'login' => :new
    	post 'login' => :create
    	get 'logout' => :destroy
    end

    root :to => 'sessions#new' 
  end
  match '/:locale' => 'sessions#new' , :as => "/login"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :email, :name, :password_digest, :time_zone
  attr_accessible :password, :password_confirmation, :avatar, :notification
  attr_accessible :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at
  
 
  has_many :messages#, :dependent => :destroy
  has_many :flag_messages, :dependent => :destroy
  has_many :receivers, :dependent => :destroy
  has_many :authentications
  has_many :oauths
  
  
  validates_attachment_size :avatar, :less_than=>1.megabyte, :message => "Image size too large"
  validates_attachment_content_type :avatar, :content_type=>['image/jpeg', 'image/png', 'image/gif', 'image/jpg'], :message => "Please upload a image of jpg/png format"
  validates :name, :presence => true,:length => { :minimum => 3,:tokenizer => lambda {|str| str.scan(/[a-z]/i)}}
  validates :email, :uniqueness => {:case_sensitive => false}, :presence => true 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :age, :numericality => {:only_integer => true ,:greater_than => 0 , :less_than => 100 },:allow_nil => true
  validates :password, :presence => true,:length => { :minimum => 6 }, :if => :password
  
  has_attached_file :avatar ,:styles => {:small => "120x120>",:thumb => "50x50>"}
  
  has_secure_password 
  

  after_create :welcome
 
  scope :join_with_receiver, joins("as u inner join receivers as r on r.user_id = u.id")
  
  def name_with_email
     user = User.find self.id
    "#{self.name}<#{user.email}>"
  end


  def apply_omniauth(omniauth)
    if omniauth['provider'] != 'twitter'
      self.email = omniauth['info']['email'] if email.blank?
    end  
    self.name  = omniauth['info']['name'] if name.blank?
    self.notification = "1"
    self.time_zone = "New Delhi"
    self.password = self.password_confirmation = self.name
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid']) 
  end

  def welcome
    Notifier.delay.welcome_message(self)
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authorize, only: [:create, :new, :user_verify, :send_password]
  skip_before_filter :authorize_through_json
  before_filter :check_user_not_loggedin, :only => [:user_verify]

  autocomplete :user, :name, :display_value => :name_with_email
  


  caches_action :user_verify, :layout => false


  def change_avatar
    @user = current_user
  end
  def change_time_zone
    @user = current_user
  end
  def change_notification
    @user = current_user
  end
  
  def user_verify
    @user = User.new
  end
  
  def send_password
   @user = User.find_by_name_and_email(params[:user][:name],params[:user][:email])
   if @user
      pass = SecureRandom.urlsafe_base64(n=6)
      @user.update_attributes({:password => pass})
      Notifier.send_password(@user,pass).deliver
   end   
   respond_to do |format|
     flash[:notice] = @user ? 'A mail has been sent to you' : "Your entry Doesn't match our record"
     format.html { redirect_to request.referrer }
   end 
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        flash[:notice]= "User #{@user.name} was successfully created."
        format.html { redirect_to login_path}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def succesful_updation
     flash[:notice] = "User #{current_user.name} was successfully updated"
     redirect_to inbox_path 
  end  

  def update_notification
    current_user.update_attribute(:notification, params[:notification])
    succesful_updation
    
  end

  def update_time_zone
     current_user.update_attribute(:time_zone, params[:user][:time_zone])
     succesful_updation
  end
  
  def update_picture
    if params[:user] && current_user.update_attributes({:avatar => params[:user][:avatar]})
       succesful_updation
    else
       flash[:error] = params[:user] == nil ? "Please update a photo" : "Please update a photo of jpg/png type"
       redirect_to request.referrer   
    end
  end

  def update
     if current_user.authenticate(params[:user][:old])
       params[:user].delete :old
       if current_user.update_attributes(params[:user])
         succesful_updation
         return
       else
         flash[:error] = "Password is empty or doesnt matches"
       end
     else
         flash[:error] = "Old password doesn't match"
     end
     redirect_to edit_user_path(current_user.id)
   end
end

app/views/users/_form.html.erb
<div class="depot_form">
  <%= form_for @user,:html => { :multipart => true}  do |f| %>
    <fieldset>
      <legend><%= t :enter_details, :scope => [:users, :new] %></legend>
      <table>
        <tr>
          <td><%= f.label :name %></td>
          <td><%= f.text_field :name, size: 40 %></td>
          <td><% if @user.errors[:name].any? %><div id="errors"><%= @user.errors.get(:name).join(', ') %></div><% end %></td>
       </tr>
       <tr>
          <td><%= f.label :email %></td>
          <td><%= f.email_field :email, size: 40 %></td>
          <td><% if @user.errors[:email].any? %><div id="errors"><%= @user.errors.get(:email).join(', ') %></div><% end %></td>
       </tr>
       <tr>
          <td><%= f.label :age %></td>
          <td><%= f.text_field :age, size: 40 %></td>
          <td><% if @user.errors[:age].any? %><div id="errors"><%= @user.errors.get(:age).join(', ') %></div><% end %></td>
       </tr>
       <tr>
          <td><%= f.label :avatar%></td>
          <td><%= f.file_field :avatar %></td>
          <td><% if @user.errors[:avatar].any? %><div id="errors"><%= @user.errors.get(:avatar_content_type).join(', ')  %><%= @user.errors.get(:avtar_file_size)  %></div><% end %></td>
       </tr>
       <tr>
          <td><%= f.label :password%></td>
          <td><%= f.password_field :password, size: 40 %></td>
          <td><% if @user.errors[:password].any? %><div id="errors"><%= @user.errors.get(:password).join(', ') %></div><% end %></td>
       </tr>
       <tr>
          <td><%= f.label :password_confirmation %></td>
          <td><%= f.password_field :password_confirmation, size: 40 %></td>
       </tr>
       <tr> 
          <td><%= f.label :time_zone%></td>
          <td>&nbsp;&nbsp;<%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all.sort,:default => "New Delhi" %></td>
       </tr>  
     </table>
     <br><br>&nbsp;&nbsp;&nbsp;&nbsp;<%= f.check_box :notification %>  <%= t('users.new.notification_receive') %>
     <div>
       <%= f.submit t('users.new.submit') %>
     </div>
   </fieldset>
  <% end %>
 </div>

app/views/users/change_avatar.html.erb
<% cache('updating_picture') do %>
<h1>Update picture</h1>
<div class="depot_form">
  <%= form_for @user,:html => { :multipart => true}  ,:url => update_picture_users_path do |f| %>
  <fieldset>
    <legend>Update New picture</legend>
    <table>
     <tr>
       <td><%= f.label :avatar%></td>
       <td><%= f.file_field :avatar %></td>
     </tr>
    </table>
    <div>
      <%= f.submit %>
    </div>
  </fieldset>
  <% end %>
</div>
<%end %>

app/views/users/change_notification.html.erb
<h1>Update Notification</h1>
<div class="depot_form">
  <%= form_for @user,:html => { :multipart => true}  ,:url => update_notification_users_path do |f| %>
  <fieldset>
    <legend>Update Notification</legend>
    <br><br>
    &nbsp;&nbsp;&nbsp;&nbsp;<%= f.check_box :notification %> Check To receive notifications from site
    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/users/change_time_zone.html.erb
<h1>Update Time Zone</h1>
<div class="depot_form">
  <%= form_for @user,:html => { :multipart => true}  ,:url => update_time_zone_users_path do |f| %>
  <fieldset>
    <legend>Update TimeZone</legend>
    <br><br>&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.label :time_zone,'Time Zone'%>  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all.sort,:default => "New Delhi" %>
    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>
  <div class="depot_form">
    <%= form_for @user do |f| %>
      <fieldset>
        <legend>Enter New Password</legend>
        <table> 
          <tr>
            <td> <%= f.label :old, 'OldPassword' %> </td>
            <td> <%= f.password_field :old, size: 40 %> </td>
          </tr>
          <tr>
            <td><%= f.label :password, 'Password' %></td>
            <% if @user.errors[:password].any? %><td class="error"><% else %><td><% end %><%= f.password_field :password, size: 40 %></td>
            <td><% if @user.errors[:password].any? %><div id="error"><%= @user.errors.get(:password) %></div><% end %></td>
          </tr>
          <tr>
            <td><%= f.label :password_confirmation, 'Confirm' %></td>
            <td><%= f.password_field :password_confirmation, size: 40 %></td>
          </tr>
        <table>
        <div>
          <%= f.submit %>
        </div>
      </fieldset>
    <% end %>
  </div>

app/views/users/new.html.erb
<div class="mm">
<h1><%= t('.new_user') %></h1>
</div>
<%= render 'form' %>

app/views/users/user_verify.html.erb
<div class="depot_form">
  <%= form_for @user,:url => send_password_users_path ,:method =>"get" do |f| %>
  <fieldset>
    <legend><%= t('users.new.enter_details') %></legend>
    <table>
      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name, size: 40 %></td>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td><%= f.email_field :email, size: 40 %></td>
      </tr>
    </table><br><br>
    <%= f.submit t('verify') %>
  </fieldset>
  <% end %>
</div>