config/routes.rb
Singlemessaging::Application.routes.draw do
  scope "(:locale)", :locale => /en|hi/ do
    resources :oauths, :only => [:destroy, :index] do
       get :generate, :on => :collection
    end

    match '/auth/:provider/callback' => 'authentication#create'
    get "authentication/index"
    get "authentication/fill_email"
    post "authentication/change_email"
    get "authentication/create"

    get "authentication/destroy"
   # get "sessions/new"
    get "sessions/create"
    #get "sessions/destroy"
    #get "sessions/set_locale"
    get "sessions/faq"


    match "/inbox" => "messages#inbox", :as =>"inbox", :via =>"get"
    match "/reply" => "messages#reply", :as =>"reply", :via =>"post"
    resources :messages, :except => [ :update,:index] do
      member do
        get :downloads
      end
      collection do
        get 'destroy' => :destroy
        put :index_delete
        put :show_delete
        get :drafts
        get :outbox
        put :flag
        put :send_draft  
      end 
    end 


    resources :users, :except => [:destroy, :show, :index] do
       get :autocomplete_user_name, :on => :collection
      collection do   
        get :change_time_zone 
        put :update_time_zone 
        get :change_avatar 
        put :update_picture
        get :change_notification 
        put :update_notification
        get :user_verify 
        get :send_password
      end 
    end

    controller :sessions do
    	get 'login' => :new
    	post 'login' => :create
    	get 'logout' => :destroy
    end

    root :to => 'sessions#new' 
  end
  match '/:locale' => 'sessions#new' , :as => "/login"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :uid, :provider
  belongs_to :user
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  
  skip_before_filter :authorize , :except => [:index, :destroy]
  skip_before_filter :authorize_through_json
  def index
    @authentications = current_user.authentications 
  end

  def create
     omniauth = request.env["omniauth.auth"]
     authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
     if authentication && !current_user
       flash[:notice] = "Signed in successfully using #{omniauth['provider']}"
       session[:user_id] = authentication.user.id
       redirect_to inbox_url
     elsif current_user
        if !authentication
           current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
           flash[:notice] = "Authentication successful"
        else
           flash[:error] = "Already linked"
        end
         redirect_to authentication_index_url 	
     else
        create_user(omniauth) 
     end
  end
  
  def create_user(omniauth)
    user = User.new
    user.apply_omniauth(omniauth)
    if user.email != nil && !User.find_by_email(user.email) && user.save 
      flash[:notice] = "User account created succesfully update your time zone"
      session[:user_id] = user.id
      redirect_to change_time_zone_users_url
    elsif User.find_by_email(user.email)
      flash[:notice] ="Already an account exist with #{user.email}"
      redirect_to login_url
    else
      flash[:notice] ="Third party does not provide some infos regarding you please fill it"
      session[:omniauth] = omniauth.except('extra')
      redirect_to authentication_fill_email_url
    end
  end  

  def fill_email 
     @user =User.new
  end
  
  def change_email
    @user = User.new
    @user.apply_omniauth(session[:omniauth])
    @user.email = params[:user][:email]
    respond_to do |format|
      if @user.save
         flash[:notice] = "User account created succesfully update your time zone"
         session[:user_id] = @user.id
         session[:omniauth] = nil
         format.html {redirect_to change_time_zone_users_url}
      else
         format.html { render action: "fill_email" }
      end
    end 
  end	


  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentication_index_url
  end
end

app/views/authentication/_list.html.erb
<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter.png", :size => "50x50", :alt => "Twitter" %>
  <%= t('twitter') %>
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook.png", :size => "50x50", :alt => "Facebook" %>
  <%= t('facebook') %>
</a>

<a href="/auth/linkedin" class="auth_provider">
  <%= image_tag "linkedin.png", :size => "50x50", :alt => "Linkedin" %>
  <%= t('linkedin') %>
</a>
<div class="clear"></div>

app/views/authentication/fill_email.html.erb
<div class="depot_form">
  <%= form_for @user, :url => authentication_change_email_url do |f| %>
    <fieldset>
      <legend>Enter Email</legend>
      <table>
      
       <tr>
          <td><%= f.label :email %></td>
          <td><%= f.email_field :email, size: 40 %></td>
          <td><% if @user.errors[:email].any? %><div id="errors"><%= @user.errors.get(:email).join(', ') %></div><% end %></td>
       </tr>
       </table>
       <%= f.submit %>
     </div>
   </fieldset>
  <% end %>
 </div>

app/views/authentication/index.html.erb
<h3><%= "Linked Accounts" %></h3>
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "authentication" %>
<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="box">
          <%= image_tag "#{authentication.provider}.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.uid %></div>
          
          <%= link_to "X", authentication_destroy_url(:id => authentication.id), :confirm => 'Are you sure you want to remove this authentication option?', :method => :get, :class => "remove" %>
          
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <br><br><br>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>

  <p><strong>Sign in through one of these services:</strong></p>
<% end %>
<%= render 'list' %>