config/routes.rb
Singlemessaging::Application.routes.draw do
  scope "(:locale)", :locale => /en|hi/ do
    resources :oauths, :only => [:destroy, :index] do
       get :generate, :on => :collection
    end

    match '/auth/:provider/callback' => 'authentication#create'
    get "authentication/index"
    get "authentication/fill_email"
    post "authentication/change_email"
    get "authentication/create"

    get "authentication/destroy"
   # get "sessions/new"
    get "sessions/create"
    #get "sessions/destroy"
    #get "sessions/set_locale"
    get "sessions/faq"


    match "/inbox" => "messages#inbox", :as =>"inbox", :via =>"get"
    match "/reply" => "messages#reply", :as =>"reply", :via =>"post"
    resources :messages, :except => [ :update,:index] do
      member do
        get :downloads
      end
      collection do
        get 'destroy' => :destroy
        put :index_delete
        put :show_delete
        get :drafts
        get :outbox
        put :flag
        put :send_draft  
      end 
    end 


    resources :users, :except => [:destroy, :show, :index] do
       get :autocomplete_user_name, :on => :collection
      collection do   
        get :change_time_zone 
        put :update_time_zone 
        get :change_avatar 
        put :update_picture
        get :change_notification 
        put :update_notification
        get :user_verify 
        get :send_password
      end 
    end

    controller :sessions do
    	get 'login' => :new
    	post 'login' => :create
    	get 'logout' => :destroy
    end

    root :to => 'sessions#new' 
  end
  match '/:locale' => 'sessions#new' , :as => "/login"

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Vinsol Messenger</title>
  <%= stylesheet_link_tag "application" %>
  <%= yield(:head) -%>
  <%= csrf_meta_tag %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">

  <div id="banner">
    <%= image_tag("vinsol.jpg") %>
    <%= @page_title || t('.vinsol_messenger') %>
   <div id="user">  <%= t('.welcome') %>
   <% if session[:user_id]!=nil %> 
   <%= (User.find session[:user_id]).name%>
   <h3><%= link_to 'Log Out',logout_path,:method=>:delete%></h3>
   <%else%>
    <%= t('.guest') %>
   <%end%>
   </div>
  </div>
  <div id="columns">
    <div id="side">
      <ul>
        <% if session[:user_id]==nil %> 
        <li><%= link_to t('.new_user'), new_user_path %></li>
        <li><%= link_to t('.home'), login_path %></li>
        <li><%= link_to t('.forgot_password'), user_verify_users_path %></li>
        <li><%= link_to t('.faq'), sessions_faq_path %></li>
        <li><%= link_to t('.english'), :locale => :en %></li>
        <li><%= link_to t('.hindi'), :locale => :hi %></li>
        <% else %>
        <% if (User.find session[:user_id]).avatar.exists? %>
          <%= image_tag (User.find session[:user_id]).avatar.url(:small) %>
        <% else %>
          <%= image_tag("no.jpg") %>
        <% end %>

          <li><%= link_to 'Compose Message', new_message_path %></li>
          <li><%= link_to 'Inbox', inbox_path %></li>
          <li><%= link_to 'Outbox', outbox_messages_path %></li>
          <li><%= link_to 'Drafts',  drafts_messages_path%></li>
          <li><%= link_to 'Update Avatar', change_avatar_users_path%></li>
          <li><%= link_to 'Create token', generate_oauths_path %></li>
          <li><%= link_to 'Show tokens', oauths_path %></li>
          <li><%= link_to 'Update Notifications', change_notification_users_path%></li>
          <li><%= link_to 'Update Timezone', change_time_zone_users_path%></li>
          <li><%= link_to 'Link more accounts', authentication_index_url %></li>
          <li><%= link_to 'Update Password', edit_user_path(session[:user_id]) %></li>
          
        <%end%>
      </ul>
    </div>
    <div id="main">
      <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, :id => key %>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>